# Artificial Neural Network

### Importing the libraries

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [6]:
tf.__version__

'2.2.0'

# New Section

## Part 1 - Data Preprocessing

### Importing the dataset

In [8]:
dataset=pd.read_excel("Folds5x2_pp.xlsx")
X=dataset.iloc[ : , :-1].values
Y=dataset.iloc[ : , -1].values

In [9]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [10]:
print(Y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.20,random_state=0)

In [12]:
print(X_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [13]:
print(Y_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


In [14]:
print(X_test)

[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]


In [15]:
print(Y_test)

[431.23 460.01 461.14 ... 473.26 438.   463.28]


## Part 2 - Building the ANN

### Initializing the ANN

In [17]:
ann=tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [18]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the second hidden layer

In [19]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the output layer

In [21]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [23]:
ann.compile(optimizer='adam',loss='mean_squared_error')

### Training the ANN model on the Training set

In [24]:
ann.fit(X_train,Y_train,batch_size=32,epochs=100)

Epoch 1/100
240/240 [==============================] - 0s 1ms/step - loss: 68898.7031
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 462.2389
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 450.1168
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 434.6721
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 416.5014
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 396.8958
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 374.7358
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 351.7093
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 327.3152
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 301.0289
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 276.3280
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - lo

### Predicting the results of the Test set

In [31]:
Y_pred=ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[433.64 431.23]
 [464.77 460.01]
 [468.24 461.14]
 ...
 [475.53 473.26]
 [442.25 438.  ]
 [461.5  463.28]]


In [27]:
from sklearn.metrics import r2_score
print(r2_score(Y_test,Y_pred))

0.8959689816872037


In [28]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(Y_test,Y_pred))

30.427807371416044


In [29]:
s=0
from math import pow
for i in range(len(Y_test)):
  s=s+pow((Y_pred[i]-Y_test[i]),2)
print(s/len(Y_test))

30.42780828993094
